lorem_text = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget egestas sem. Curabitur feugiat condimentum elementum. Curabitur vel eros ut nisi interdum interdum a a enim. Nunc eu massa ut lacus accumsan tempor sed sed ante. Vivamus elementum nibh sed quam ornare a lacinia nisi euismod. Suspendisse ac metus dui, et suscipit nisl. Nullam purus enim, consectetur vitae interdum ac, commodo vel erat. Fusce quam tortor, imperdiet a porttitor non, feugiat vitae libero. Etiam in metus nulla, quis viverra dolor. In hac habitasse platea dictumst. Nullam interdum imperdiet vestibulum. Praesent quis felis augue, sed volutpat est. Phasellus mollis felis eu nulla commodo vitae laoreet arcu congue.

Nullam in commodo purus. Vestibulum nec turpis nec turpis malesuada tincidunt. In hac habitasse platea dictumst. In sagittis, nisi nec volutpat ultrices, mauris magna congue sapien, feugiat scelerisque tellus orci in eros. Nam urna dolor, dapibus a consequat et, auctor eget orci. Nunc pharetra porttitor est, quis tincidunt sapien consectetur id. Pellentesque condimentum, libero in pharetra condimentum, turpis quam varius ipsum, ut tincidunt augue dui vel diam. Nullam massa nibh, ornare vel ornare sed, tristique sed diam. Nulla euismod leo purus. Fusce rhoncus felis in leo blandit faucibus nec eu justo. Quisque porttitor dolor a mi laoreet vehicula. Aliquam eu orci et quam molestie posuere. Pellentesque vitae nibh sapien. Curabitur accumsan aliquet imperdiet. Donec justo odio, aliquam ut congue sed, hendrerit a lectus. Cras sed eros ipsum, eu viverra sapien.

Nulla porta magna non dui ullamcorper interdum et quis quam. Nulla vitae libero non velit sollicitudin laoreet in ut mi. Donec eu nisl eget augue volutpat pretium euismod et massa. Pellentesque sit amet quam est. Nullam rhoncus imperdiet urna, volutpat suscipit enim tristique vitae. Aliquam suscipit neque et quam interdum malesuada. Donec non ante sit amet elit iaculis porta. Aenean urna lorem, tempus a ultrices a, venenatis et nisi.

Duis viverra, neque tincidunt faucibus adipiscing, massa nibh volutpat velit, eget dapibus risus ipsum quis massa. Phasellus vitae felis et massa lacinia ornare. Aliquam mi sem, egestas ut sagittis id, blandit lacinia diam. Maecenas semper posuere neque accumsan mollis. Vivamus vel tortor ut mauris pellentesque hendrerit ac sit amet ante. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi dignissim, sem quis suscipit tincidunt, justo orci aliquam nulla, nec tempus lacus massa vitae ligula. Quisque feugiat accumsan diam ut vulputate. Duis neque metus, accumsan ut semper elementum, sodales a lorem. Vivamus vestibulum mattis velit, in dictum lacus sodales eu. Maecenas porttitor neque nec elit tincidunt euismod.

Nam in tristique felis. Integer a eros a est venenatis ornare. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam eu auctor neque. Fusce egestas odio bibendum eros gravida imperdiet congue sapien imperdiet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut ornare aliquam ante in consequat. Pellentesque ac magna id sapien fringilla luctus non non sem. Nam mattis dolor eget ante ultricies blandit. Suspendisse imperdiet pellentesque scelerisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet mi sit amet ante aliquet elementum. Suspendisse dictum suscipit metus ac cursus. Suspendisse at ornare enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Quisque justo elit, ultrices sit amet tristique vitae, auctor sagittis ligula. Nunc eu sollicitudin dolor. Morbi lectus lectus, aliquam et pharetra at, sodales eu massa. Duis quis nulla sit amet justo gravida cursus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus vel est justo. Nullam congue auctor pellentesque. Vestibulum ac augue at neque imperdiet fringilla sit amet at dui. Quisque sed velit dui, at feugiat massa. Mauris eu ante eros. Proin laoreet ligula a lorem lacinia iaculis. Pellentesque a augue eu ante pharetra pretium. In suscipit, sapien sed gravida pulvinar, purus turpis tempus metus, ac suscipit justo dolor in diam. Etiam at diam diam, ut volutpat nibh. In rhoncus nibh a ligula fermentum vitae egestas elit aliquam.

Integer pharetra ullamcorper mauris vehicula euismod. In id orci est, in convallis odio. Integer tempus ultrices lorem, quis molestie metus ultricies vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla non suscipit quam. Etiam in ultricies tellus. Fusce vehicula, enim non viverra commodo, dolor turpis egestas erat, ut hendrerit mauris sem nec ligula. Mauris commodo ligula non mauris aliquet elementum. Vestibulum iaculis tellus sed ipsum malesuada a volutpat ligula imperdiet. Sed nisi lacus, pulvinar at semper nec, convallis sed sem. Fusce placerat felis ac ligula scelerisque sit amet pretium tortor tristique. Sed in risus aliquet felis placerat cursus vel in justo. Nullam iaculis rhoncus ligula, nec posuere ligula pretium id. Morbi elementum dolor eget nisl ullamcorper fringilla.

Donec lacus metus, pellentesque vitae adipiscing volutpat, convallis ac enim. Maecenas nisl dui, viverra vel vulputate eu, venenatis dapibus eros. Vestibulum rutrum, justo quis laoreet laoreet, sem libero imperdiet mauris, vel fringilla felis diam quis purus. Praesent id placerat enim. Suspendisse nec neque bibendum orci facilisis viverra et ut sapien. Vestibulum ac nisl lacus, eget facilisis enim. Suspendisse non dui eros, eu fermentum metus. Morbi aliquet semper aliquet.

Duis sit amet mi ipsum, sit amet cursus urna. Donec nec magna tortor, et iaculis tortor. Aliquam quam tortor, dapibus quis volutpat ut, tempor eu nisi. Suspendisse potenti. Nulla volutpat blandit enim, eget fermentum ipsum suscipit eu. Suspendisse potenti. Ut suscipit tempor ipsum, in elementum lectus cursus eget. Vivamus commodo, lectus eget aliquet imperdiet, nisi tellus pellentesque odio, nec adipiscing dui nibh eget justo. Aenean commodo ultrices malesuada. Fusce ut ipsum gravida lorem euismod egestas at interdum diam. Morbi gravida sodales ligula, at scelerisque ipsum placerat nec. Praesent sollicitudin, purus nec rhoncus porta, diam ante tincidunt justo, adipiscing euismod dolor leo nec dui. Etiam est justo, sagittis quis dignissim vitae, laoreet ac erat. Maecenas egestas blandit viverra. Sed ultricies enim non erat posuere at suscipit mi facilisis. Ut eget risus dapibus lacus malesuada imperdiet non eleifend risus.

Etiam at est urna, quis laoreet lorem. Sed faucibus laoreet porttitor. Sed nec nunc eros, ut lacinia justo. Pellentesque id urna nunc. Fusce adipiscing sapien a orci luctus hendrerit. Morbi imperdiet diam ac diam pulvinar in pellentesque sem volutpat. Aliquam convallis accumsan feugiat. Vestibulum ut cursus nisl. Praesent faucibus, eros ac volutpat dapibus, risus nisl eleifend libero, non egestas nibh neque sit amet velit. Pellentesque viverra sem a elit dapibus aliquam molestie nisl blandit. Maecenas porta sodales ante, sit amet dapibus leo vestibulum eu. Etiam congue venenatis nisl, ac pretium quam ullamcorper ut. Donec tempus aliquet nulla, ut porttitor metus tristique sed.

Vestibulum rutrum euismod diam, sed posuere lacus adipiscing et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Fusce quam urna, adipiscing a tincidunt ut, blandit semper turpis. Morbi tempus malesuada felis, auctor posuere justo laoreet a. Sed feugiat rutrum ultrices. Aliquam erat volutpat. Duis sit amet orci ligula, quis elementum massa. Nullam pretium, dolor et rutrum faucibus, ante leo tincidunt elit, ac pellentesque lacus felis a ligula. Vestibulum orci enim, rutrum a pharetra nec, vestibulum sit amet quam.

Nulla varius facilisis laoreet. Nullam a ligula elit. Pellentesque eu nisi ut nisi viverra cursus nec et velit. Mauris nisi lacus, iaculis id ultrices nec, tempor et ipsum. Suspendisse tincidunt, mi ac suscipit volutpat, risus risus volutpat orci, in laoreet mi sapien eu risus. Integer erat nibh, feugiat eget congue id, faucibus nec elit. Mauris lectus ligula, viverra malesuada dapibus non, lacinia id turpis. Suspendisse placerat ultricies nibh, eget porttitor augue convallis id. Quisque at nulla porta velit interdum consequat elementum ac urna. Maecenas blandit mollis rhoncus.

Etiam tempus, tellus sit amet feugiat egestas, nisl felis pellentesque eros, vel euismod arcu ipsum sed libero. Nulla facilisi. Praesent interdum neque et justo vestibulum gravida eget id sapien. Pellentesque aliquam porta tortor vel consequat. Praesent fermentum eros non elit aliquam vitae feugiat tellus tempus. Proin non tellus facilisis magna condimentum sollicitudin quis eget dolor. Morbi iaculis hendrerit lorem, vel volutpat libero laoreet in. Nam at neque sit amet libero laoreet consequat a et eros. Proin ultrices nisi ut sapien laoreet a blandit massa dignissim.

Fusce eu lacus sem. Pellentesque mollis eros ac turpis facilisis vitae malesuada dui tempor. Curabitur dignissim ipsum in quam lacinia sit amet pellentesque urna porta. Proin eu elementum felis. Phasellus vestibulum ligula sapien. Maecenas eleifend, magna vitae auctor dignissim, neque felis adipiscing erat, ac iaculis velit ipsum eu justo. Sed at sem orci, accumsan fringilla sem. Praesent tempor, ligula ut rutrum molestie, odio augue tristique libero, eu imperdiet augue purus eu nisi. Sed consequat elementum mi et lacinia.

Donec lorem nisl, porttitor in semper sit amet, molestie sed sem. Vivamus pretium orci eget odio lacinia volutpat. Aliquam accumsan dolor quis mauris suscipit vulputate. Donec cursus, massa ut facilisis suscipit, justo quam malesuada dui, vitae venenatis erat augue ac arcu. Quisque quis tellus vitae lorem ornare sodales at vel mi. Sed sollicitudin sodales metus, id scelerisque justo elementum sit amet. Ut et sodales nunc. Donec tortor nisi, blandit in sodales in, laoreet nec orci. Maecenas ut erat massa.

Maecenas vitae justo lorem, at congue tellus. Sed sit amet justo nec massa ultrices bibendum quis id magna. Vestibulum in odio ut augue facilisis sodales vitae a sem. In eleifend elit sed sem rutrum non tempus lorem pharetra. Nam iaculis rhoncus est, lobortis congue mauris varius nec. Donec et ipsum metus. Mauris in mauris magna, quis posuere turpis. Phasellus pellentesque quam eu nibh dapibus lobortis. Nam hendrerit sollicitudin diam nec cursus. Donec lectus velit, aliquet ultricies tincidunt a, malesuada eget diam.

Duis accumsan sem sed felis tempus volutpat. Integer neque nulla, sodales a suscipit vel, interdum sit amet nisi. Phasellus vulputate fermentum augue, vitae tempus odio vehicula a. In hac habitasse platea dictumst. Mauris sit amet enim vitae justo pellentesque interdum. Aliquam erat volutpat. Suspendisse non nisl vel est scelerisque laoreet ut sed tortor. Ut pharetra lobortis odio non vulputate. Sed quis metus mi. Cras elementum, dolor at tempor condimentum, justo leo aliquam leo, et imperdiet lacus tellus id eros. Nullam a accumsan tellus. Nullam laoreet venenatis est, a aliquet risus sollicitudin sit amet. Mauris eu dolor nisi, nec hendrerit mauris. Mauris ac augue velit, a faucibus urna. Pellentesque tincidunt, justo ut lobortis scelerisque, est velit hendrerit lectus, sit amet lacinia justo quam et mauris. Curabitur dignissim rhoncus gravida.

Donec fringilla venenatis elit, ac bibendum mi vulputate ut. Aenean ut justo eu libero lobortis posuere in vel sem. Aenean cursus congue vestibulum. Aenean pharetra viverra luctus. Quisque pharetra libero elementum libero eleifend in ultrices nisi congue. Quisque non diam lacus, ut vulputate mauris. Quisque nec tellus lectus, vitae laoreet velit. Ut vitae nibh justo, quis varius nulla. Quisque posuere ultricies augue at fringilla. Morbi turpis diam, posuere sit amet vehicula non, bibendum at turpis. In at sollicitudin mi. Sed commodo vulputate interdum.

Donec adipiscing fringilla purus, nec aliquet justo pretium in. Ut vestibulum dapibus lectus, in blandit erat hendrerit a. Sed pretium mi posuere libero sagittis viverra. Maecenas aliquet, neque et commodo tempor, odio sapien fermentum sem, at porttitor nisi quam sit amet dui. Sed elit risus, auctor viverra varius sed, aliquet in est. In erat massa, ullamcorper in fermentum quis, lacinia quis arcu. Cras eget mauris ac sem faucibus suscipit vitae vitae velit. Pellentesque luctus, sapien nec aliquam convallis, ligula eros iaculis massa, a vehicula eros felis egestas purus. Suspendisse ornare, nibh porta malesuada vehicula, nulla ligula ultrices libero, vel posuere tellus ipsum at mauris. Nunc felis dui, euismod at suscipit non, malesuada vitae erat.

Maecenas auctor consequat malesuada. Praesent faucibus accumsan fermentum. Nunc sed nunc laoreet quam dignissim imperdiet sit amet dignissim velit. Praesent laoreet tempor neque, malesuada gravida augue adipiscing vel. Sed libero libero, tempor non feugiat dictum, ornare eget magna. Aliquam sit amet lacus quam, eget faucibus est. Mauris eu eros et sem hendrerit pulvinar. Suspendisse potenti. Maecenas scelerisque, velit mollis tempus egestas, nisl justo eleifend odio, in imperdiet nunc lacus eu justo. Fusce metus massa, interdum eget imperdiet sed, varius non nulla. Pellentesque sit amet elit nec est tempor placerat. Sed convallis risus ut magna fermentum elementum porta velit dictum."""

message_len = 90

def make_message(i):
    message_start_offest = (i % ((len(lorem_text) / message_len) - 1)) * message_len
    message = lorem_text[message_start_offest:message_start_offest+message_len]
    return {
        'title' : 'Message Title %s' %(i+1),
        'message' : message
    }
